project-koku/koku-metrics-operator

- controllers/costmanagement_controller.go
> Fix typo in reconciling log

- Makefile
- README.md
* Quick make command update to deploy current branch
> Simplify deployment of dev branches.

- Dockerfile
- controllers/costmanagement_controller.go
- crhchttp/config.go
- crhchttp/http_cloud_dot_redhat.go
* Restructure some code from the controller
* Create a utils package to hold communication to cloud.redhat.com
> Extract out the Http communication with cloud.redhat.com and Config object.

- crhchttp/http_cloud_dot_redhat.go
Tested using basic auth with no validation for CI and using token auth/validation for PROD.
> Utilize the validate_cert spec boolean and add cert verification

- .github/workflows/unittests.yaml
- Makefile
- run unittests
- upload coverage to Codecov
> Add github-actions

- controllers/costmanagement_controller.go
- crhchttp/http_cloud_dot_redhat.go
- sources/handler.go
- sources/handler_test.go
> COST-395 Sources unittests

- api/v1alpha1/kokumetricsconfig_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- api/v1beta1/kokumetricsconfig_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- config/samples/air-gapped.yaml
- config/samples/koku-metrics-cfg_v1alpha1_kokumetricsconfig.yaml
- controllers/kokumetricsconfig_controller.go
- controllers/kokumetricsconfig_controller_test.go
- controllers/suite_test.go
1. after first upload failure, do not try the rest
2. if upload_toggle is false, do not set or check authentication, do not check sources, do not upload files
> do not check auth when toggle-upload is false

- Makefile
- PROJECT
- api/v1alpha1/kokumetricsconfig_types.go
- config/manifests/bases/koku-metrics-operator.clusterserviceversion.yaml
- config/samples/kustomization.yaml
- docs/csv-description.md
- koku-metrics-operator/0.9.4/Dockerfile
- koku-metrics-operator/0.9.4/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- koku-metrics-operator/0.9.4/manifests/koku-metrics-operator.clusterserviceversion.yaml
- koku-metrics-operator/0.9.4/metadata/annotations.yaml
1. remove v1alpha1 from served versions
2. add beta upgrade channel
> release-v0.9.4

- Makefile
- docs/csv-description.md
- koku-metrics-operator/0.9.5/Dockerfile
- koku-metrics-operator/0.9.5/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- koku-metrics-operator/0.9.5/manifests/koku-metrics-operator.clusterserviceversion.yaml
- koku-metrics-operator/0.9.5/metadata/annotations.yaml
- scripts/txt_replace.py
> create v0.9.5 bundle

- Makefile
- collector/prometheus.go
- scripts/txt_replace.py
Sync the upstream changes before our official builds are cut
> Pull in changes from the 0.9.6 upstream release

- Makefile
- koku-metrics-operator/0.9.7/Dockerfile
- koku-metrics-operator/0.9.7/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- koku-metrics-operator/0.9.7/manifests/koku-metrics-operator.clusterserviceversion.yaml
- koku-metrics-operator/0.9.7/metadata/annotations.yaml
https://github.com/operator-framework/community-operators/pull/3583
> v0.9.7 bundle

- Makefile
- koku-metrics-operator/0.9.8/Dockerfile
- koku-metrics-operator/0.9.8/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- koku-metrics-operator/0.9.8/manifests/koku-metrics-operator.clusterserviceversion.yaml
- koku-metrics-operator/0.9.8/metadata/annotations.yaml
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/60
> v0.9.8 bundle 

- koku-metrics-operator/0.9.8/manifests/koku-metrics-operator.clusterserviceversion.yaml
Fix the quay repo listed in the 0.9.8 csv
> Fix 0.9.8 CSV 

- config/crd/bases/costmanagement-metrics-cfg.openshift.io_costmanagementmetricsconfigs.yaml
update costmanagementmetricsconfig CRD
> Update CRD to have new fields 

- config/manifests/bases/koku-metrics-operator.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
- config/scorecard/bases/config.yaml
- config/scorecard/kustomization.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
- docs/release-testing.md
- docs/releasing.md
- scripts/txt_replace.py
1. needed to add scorecard
2. updated testing/release docs
3. fixed script for fixing dockerfile
> some additional updates after upgrade to operator-sdk v1.10

- .github/workflows/pre-commit.yaml
- .github/workflows/unittests.yaml
- .pre-commit-config.yaml
- go.mod
- fix the pre-commit configuration
- update the unit test github-action to pull go 1.16
- set go version to 1.16 in go.mod
> various versioning updates

- Dockerfile
- docs/csv-description.md
1. update build stage to use ubi8/go-toolset image
2. update out of date docs links
> use the ubi8-go-toolset image for build stage

- go.mod
- go.sum
Bump gogo/protobuf version to deal with dependabot alert
> fix dependabot alert for gogo/protobuf

- controllers/suite_test.go
- storage/storage.go
- storage/storage_test.go
* fixes volume mounting on new deployment name
> fix deployment name

- api/v1beta1/metricsconfig_types.go
- config/crd/bases/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- docs/csv-description.md
> [COST-3446] - Enable ROS metrics collection by default

- .gitignore
- Makefile
- docs/local-development.md
* add command to get necessary token and certs from cluster for local operator deployments
> add Makefile command and update local dev docs

- Makefile
- api/v1beta1/defaults.go
- api/v1beta1/metricsconfig_types.go
- config/crd/bases/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- controllers/kokumetricsconfig_controller.go
- controllers/kokumetricsconfig_controller_test.go
- crhchttp/http_cloud_dot_redhat.go
- docs/cr-example.md
- docs/csv-description.md
- docs/local-development.md
- sources/handler.go
- sources/handler_test.go
> Update API URL from cloud.redhat.com to console.redhat.com

- api/v1beta1/metricsconfig_types.go
- docs/csv-description.md
- Hold off on replacing `source` terminology with `integration` in operator docs
> Do not replace source with integration yet

- collector/collector.go
- collector/collector_test.go
[COST-4418](https://issues.redhat.com/browse/COST-4418)
> [COST-4418] safely convert provider-id to string

- Makefile
- config/manifests/bases/koku-metrics-operator.clusterserviceversion.yaml
Update the feature annotations based on:
https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs
> [COST-4579] - update features annotations

- .snyk
- exclude test files
- exclude the scripts dir because these are only helpers for dev
> more snyk exclusions

- .github/workflows/ci-manual.yaml
- Makefile
- config/crd/bases/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
Purpose:
this PR enables ci unit test in s390x by creating a zvsi on ibm cloud via github actions
Steps:
create cloud specific resources(key,vpc,subnet,floating-ip,instance etc)
connect to instance via ssh
a) clone repo
b) install go
c) run unit test
cleanup the required resources
Additional steps:
the following secrets needs to be created for action to work
-IBMCLOUD_API_KEY
-IBMCLOUD_RESOURCE_GROUP_ID
-ZVSI_PRIVATE_KEY
-ZVSI_PUBLIC_KEY
> Enable CI Test case for IBM Z(s390x) - Manual and pr target

- .github/workflows/ci-manual.yaml
The pull_request_target seems to not work. This PR will disable that trigger until we can investigate further.
We have the manual workflow as a workaround in the meantime.
> disable s390x pull_request_target

- api/v1beta1/metricsconfig_types.go
- config/crd/bases/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- docs/csv-description.md
- internal/controller/kokumetricsconfig_controller.go
[COST-4115](https://issues.redhat.com/browse/COST-4115)
This change will add an updated deprecation notice and guidance to transition off basic auth.
> [COST-4115] Add basic auth deprecation notice and transition guidance

- Makefile
- costmanagement-metrics-operator/3.3.0/Dockerfile
- costmanagement-metrics-operator/3.3.0/manifests/costmanagement-metrics-cfg.openshift.io_costmanagementmetricsconfigs.yaml
- costmanagement-metrics-operator/3.3.0/manifests/costmanagement-metrics-operator.clusterserviceversion.yaml
- costmanagement-metrics-operator/3.3.0/metadata/annotations.yaml
- docs/csv-description.md
- docs/generate-downstream.md
* fix the downstream command
* add the downstream bundle
> update docs and fix make downstream

- Makefile
- koku-metrics-operator/3.3.0/Dockerfile
- koku-metrics-operator/3.3.0/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- koku-metrics-operator/3.3.0/manifests/koku-metrics-operator.clusterserviceversion.yaml
- koku-metrics-operator/3.3.0/metadata/annotations.yaml
- koku-metrics-operator/3.3.0/tests/scorecard/config.yaml
bundle for the v3.3.0 operator
> make v3.3.0 bundle

- docs/csv-description.md
[COST-5377](https://issues.redhat.com/browse/COST-5377)
> update whats new in 3.3.1

- .tekton/koku-metrics-operator-bundle-pull-request.yaml
- .tekton/koku-metrics-operator-bundle-push.yaml
- Dockerfile
- update operator bundle pipeline to only run when bundle assets are updated
> [COST-5382] konflux: update bundle pipeline and use brew registry

- .tekton/koku-metrics-operator-bundle-pull-request.yaml
- renovate.json
- add renovate configuration to reduce frequent konflux reference updates
> [COST-5534] Add renovate config

- .tekton/operator-pr.yaml
- Dockerfile
- go.mod
- [COST-5481](https://issues.redhat.com/browse/COST-5481) - upgrade to go `1.22.7`
- [COST-5533](https://issues.redhat.com/browse/COST-5533) - use ubi9 base image
> [COST-5481 | COST-5533] Update go to 1.22.7 and move to ubi9

- docs/downstream-konflux-flow.md
[COST-5373](https://issues.redhat.com/browse/COST-5373) - document konflux (build, test, release) flow for the cost management metrics operator.
> [COST-5373] document downstream konflux flow
