project-koku/koku-metrics-operator

config/crd/bases/config.openshift.io_clusterversions.yaml, controllers/costmanagement_controller_test.go, controllers/suite_test.go, go.sum
* Test empty CRD returns defaults
* Test basic auth with good secret
* Test basic auth with missing secret
```
make test                                                                                                  
/Users/chambrid/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
/Users/chambrid/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
mkdir -p /Users/chambrid/Code/cost/korekuta-operator-go/testbin
test -f /Users/chambrid/Code/cost/korekuta-operator-go/testbin/setup-envtest.sh || curl -sSLo /Users/chambrid/Code/cost/korekuta-operator-go/testbin/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/m …
```
=> Add basic controller testing.

collector/collector.go, collector/types.go
This PR fixes an error that arises when a Pod is not associated with a Node:
```
2020-10-19T15:08:24.556-0400    INFO    controllers.CostManagement      writing node results to file    {"costmanagement": "writeResults", "filename": "/tmp/cost-mgmt-operator-reports/data/cm-openshift-node-labels-lookback-202010.csv", "data set": "node"}
E1019 15:08:24.568296   71545 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x21c47e0), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x21d0ea0), missingMethod:""} (interface conversion: collector.CSVStruct is nil, not *collector.NodeRow)
```
=> Pod not on Node error

collector/prometheus.go, config/samples/trusted_ca_certmap.yaml
This PR adds a service certificate which enables TLS verification for the prometheus query requests.
This cert only works for the internal route (i.e. `https://thanos-querier.openshift-monitoring.svc:9091`). Otherwise, we will still get the `x509: certificate signed by unknown authority` error when attempting prometheus queries.
=> add service certificate

collector/collector.go, controllers/costmanagement_controller.go
- access the metav1.Time.Time. <- This cleans up a lot of logic around converting a metav1.Time variable to time.Time.
- rename base report prefixes
=> time fixes

collector/queries.go, collector/types.go, controllers/costmanagement_controller.go
- Make node reports like old reports
- Fix storage query so that namespace is added to PVC. The namespace was missed if the PVC did not have an associated Pod
- Use UTC timezone for queries and reports
=> Prometheus query/report fixes

README.md
Add doc update for pre-commit so `make lint` will run.
=> Add pre-commit setup step to README.

collector/queries.go
* Update volume queries to map with namespace to resolve uniqueness
Related to: https://issues.redhat.com/browse/COST-840
=> COST-840: Resolve many-to-many query issue.

README.md
Recently a [bug](https://issues.redhat.com/browse/COST-1003) was opened by a customer and the about section was referenced which made me realize we mentioned incorrect OCP version requirements ✊ 🆙 📈
=> Update readme with correct OCP version

crhchttp/http_cloud_dot_redhat.go
Implements an HTTP transport that uses a Proxy. The transport grabs the proxy info from the environment.
OLM should handle cluster-wide Proxy for us by adding `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` to the Pod environment. See [here](https://docs.openshift.com/container-platform/4.6/operators/admin/olm-configuring-proxy-support.html#olm-overriding-proxy-settings_olm-configuring-proxy-support).
=> COST-1008 - add proxy config to http transport

collector/prometheus.go
We run 19 total queries. With a timeout set to 90 seconds, at worst, these will consume 29 minutes. If we are still timing out after 90 seconds, then we will need a different solution for our queries.
=> COST-1259 - bump prometheus query timeout to 90 seconds

docs/csv-description.md, docs/faq.md
1. make the source creation docs a little more generic. The sources wizard should be the real guide, not the docs here.
2. added a `faqs` doc. Includes steps for forcing v0.9.4 -> v0.9.5 upgrade.
=> update source creation steps

collector/queries.go
This PR replaces some deprecated [kube-state-metrics that were removed in v2.0](https://kubernetes.io/blog/2021/04/13/kube-state-metrics-v-2-0/).
testing:
The following files should match exactly.
[new-query-results.csv](https://github.com/project-koku/koku-metrics-operator/files/6305350/e84cc634-acae-4e78-ab19-dff18d7dc673_openshift_usage_report_sorted.2.csv)
[old-query-results.csv](https://github.com/project-koku/koku-metrics-operator/files/6305355/7d3b6e1c-14d9-48a6-9ee2-90f419cab016_openshift_usage_report_sorted.2.csv)
=> COST-1287 - update queries for kube-state-metrics v2 release

controllers/kokumetricsconfig_controller.go
caught this during release testing
=> Add a statement to check if either the cluster version or cluster id isn't there

.github/workflows/pre-commit.yaml, .github/workflows/unittests.yaml, README.md
The workflows were still referencing `master` instead of `main`.
=> fix workflows

collector/queries.go, controllers/kokumetricsconfig_controller.go
This PR does 2 things:
1. Fixes queries that were gathering request/limits on pods that had exited
2. reworks the packaging logic so that old reports are packaged before an upgraded operator makes queries against prometheus.
=> COST-2096: filter requests and limits on running pods

collector/queries.go
* switch the `by (pod, namespace, node)` to `without (instance, uid)` which will prevent `many-to-many matching not allowed` errors caused by the `instance` and `uid` fields.
* add `{namespace,node,pod}!=''` because these fields are required for proper data aggregation
* add `MetricKey` to pod labels to prevent line items that are missing pod/namespace
=> [COST-2285] - fix many-to-many query error

config/default/kustomization.yaml, config/manager/manager.yaml, docs/csv-description.md
* add a new common label (`app: koku-metrics-operator`)
* add pod affinity to utilize this label
* update deployment name so that OLM will replace the old deployments (as described [here](https://github.com/operator-framework/operator-lifecycle-manager/issues/952#issuecomment-639657949)). The `commonLabels` change will add a new `selector: matchLabels:` label. `selector: matchLabels:` are immutable, so to correctly apply a new one, a deployment must be recreated.
=> add pod affinity to prevent multi-attach error

collector/queries.go
* Update the resource limits/requests queries to aggregate away the other dimensions on the right-hand side of the expression using `max()`.
* Update the usage queries to group by the same params as the limits/requests instead of relying on the `without` clause.
=> [COST-2285] - update prometheus queries for many-to-many matching error

collector/prometheus.go, collector/prometheus_test.go, collector/report_test.go
[COST-3245](https://issues.redhat.com/browse/COST-3245)
This could potentially fix an issue where the operator stops functioning during this Poll function. Adding a context with a timeout might break out of this Poll when the context is exceeded.
=> add polling context timeout

config/manager/manager.yaml
* Add annotation to ignore the kube-linter check for 3 replicas on the controller-manager
Related:
https://issues.redhat.com/browse/COST-2665
https://issues.redhat.com/browse/COST-2669
=> COST-2665: Added kube-linter ignore check for controller-manager

api/v1beta1/groupversion_info.go, controllers/kokumetricsconfig_controller_test.go, controllers/suite_test.go, dirconfig/dirconfig.go, storage/storage.go, storage/storage_test.go, storage/suite_test.go
This PR builds on https://github.com/project-koku/koku-metrics-operator/pull/161. Move the prefix `koku` to the API directory so that it can be imported elsewhere. When we need to change `koku` to `costmanagement`, we will only need to update one place instead of many.
=> variable reorg and simplification

controllers/kokumetricsconfig_controller.go, controllers/kokumetricsconfig_controller_test.go, packaging/packaging.go
* don't reset the LastSuccessfulPackagingTime as a mechanism for forcing packaging
* separate out the bit that actually does the packaging into `func forcePackageFiles` and call this directly
* the original `packageFiles` func calls `forcePackageFiles` after it's done the cycle check
* use a new variable `newInstall` to determine if we need to force a packaging after an upgraded operator
=> add more logic to prevent resetting the packaging time

.github/workflows/ci.yaml, api/v1beta1/defaults.go, controllers/kokumetricsconfig_controller.go, controllers/kokumetricsconfig_controller_test.go, sonar-project.properties
* Check spec for old API URL
* Apply new default API URL
=> Ignore old default API URL in Spec with new default API URL in Status

collector/prometheus.go, collector/prometheus_test.go
Sometimes the CR status will say that we are not configured against prometheus when we really are. This PR addresses that by ensuring we recheck the `PrometheusConfigured` and `PrometheusConnected` statuses if they are `false` instead of relying on the error messages (`ConfigError` and `ConnectionError`).
=> fix not-configured bug

Makefile, collector/collector.go, collector/collector_test.go, collector/prometheus.go, collector/prometheus_test.go, controllers/kokumetricsconfig_controller_test.go, controllers/prometheus.go, controllers/suite_test.go, scripts/txt_replace.py
* retry a given failed query up to 5 times
* retry an entire time range up to 5 times
* track a count of how many times a particular start time has been tried. If we've tried a range 5 times, we skip it
* we will maintain this tracking until we've had a successful query. If a success only comes after we've upgraded an operator, we will retry as far back as possible based on the retention period and the lastquerysuccesstime.
* If a success comes without updating the operator, then the missed data is not collected.
* update the txt_replace.py script to use argparse and accept an optional namespace argument so you can generate a CSV with that namespace so you can deploy the CSV without manually updating the namespace
With the changes to the script, I've been using this series of make …
=> [COST-3758] retry failed operator queries up to 5 times

config/samples/koku-metrics-cfg_v1beta1_kokumetricsconfig.yaml, controllers/kokumetricsconfig_controller.go, controllers/kokumetricsconfig_controller_test.go, docs/csv-description.md, sources/handler.go
[COST-4080](https://issues.redhat.com/browse/COST-4080)
- Use an empty string placeholder vs `INSERT-SOURCE-NAME` in the spec source name field.
- if the spec source name value is an empty string, replace it with cluster id.
=> [COST-4080] Replace default source name with cluster-uuid if CR is not updated

api/v1beta1/metricsconfig_types.go, config/crd/bases/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, controllers/kokumetricsconfig_controller.go, controllers/kokumetricsconfig_controller_test.go, docs/csv-description.md
- Make `spec.authentication.token_url `  optional to avoid error below during operator upgrade
```
error validating existing CRs against new CRD's schema for "kokumetricsconfigs.koku-metrics-cfg.openshift.io": error validating custom resource against new schema for KokuMetricsConfig koku-metrics-operator/kokumetricscfg-sample-v1beta1: [].spec.authentication.token_url: Required value
```
=> [COST-4230] make spec.authentication.token_url optional

controllers/kokumetricsconfig_controller.go, controllers/kokumetricsconfig_controller_test.go
* run the sourceCheck when the CR is first created, even if there are no files to upload.
=> source check on CR creation

config/rbac/role.yaml, controllers/kokumetricsconfig_controller.go
The Thanos Query deployment [will be updated soon](https://github.com/openshift/cluster-monitoring-operator/pull/2136) in Cluster Monitorinng Operator. Its Oauth-proxy guarding the web port before Thanos Query will be swapped to Kube-rbac-proxy. Due to new RBAC settings, the priviledge to access the web port is determined by `get` , `create` and `update` verb on the resource `prometheuses/api`. 
The JIRA task for this change is https://issues.redhat.com/browse/MON-3379
Here is a video explaining this change: https://drive.google.com/file/d/1j-22p6H7MOm7vPpA5HmAjq4EcrX4jrpj/view?usp=drive_link
=> Role patch preparing for Thanos Query API RBAC settings update

Dockerfile
The `controllers` directory [moved](https://github.com/project-koku/koku-metrics-operator/pull/212) from the root folder into `internal` and its name was changed to `controller`. The build flag that inserts the GitCommit is updated in this PR to match the new repo layout.
=> fix build flag path

config/manager/manager.yaml
This PR adds node affinity to ensure the controller is added to a node with a supported architecture. 
Reference: https://sdk.operatorframework.io/docs/advanced-topics/multi-arch/#setting-node-affinity-in-a-kubernetes-manifest
=> add node affinity for multiarch clusters

.github/workflows/build-and-publish.yaml, Makefile
Buildx is adding attestation-manifests to the multi-arch builds, e.g.:
```
{
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"digest": "sha256:edebc9e147bbc5de113c296658c94be803afc87ecfd3688fdc305a279975f085",
"size": 839,
"annotations": {
"vnd.docker.reference.digest": "sha256:2c8e1da6b1b4929e31e1199523879272fc7022c3761492a6df24a90e3c1e019f",
"vnd.docker.reference.type": "attestation-manifest"
},
"platform": {
"architecture": "unknown",
"os": "unknown"
}
},
....
```
These aren't used for anything, so this PR removes them.
These unknown manifests are causing some validation warnings:
```
$ operator-sdk bundle validate ./bundle --select-optional name=multiarch
WARN[0016] Warning: Value koku-metrics-operator.v3.2.0: check if the CSV is missing the label …
```
=> omit `provenance` in buildx to prevent unknown manifests

.github/workflows/ci.yaml, .gitignore, Makefile
- Run unit tests on all available architectures
=> multi-arch unit tests

config/manager/manager.yaml
When OLM tries to upgrade the operator, it will fail to rollout the new pod for the deployment due to RWO volume mounts.
The #141 PR resolved this by setting a preference to schedule the new pod on the name node as the existing pod. However this change was reverted in #145 for some unknown/undocumented reason.
=> Resolve deployment upgrade with RWO PVCs

.snyk
Add snyk config to exclude:
- koku-metrics-operator: this directory contains no code, and the Dockerfiles with these bundles contain false positives
- vendor: these packages are not our code to worry about
- testing: because it's testing related...
=> add .snyk config file to exclude directories

.github/dependabot.yaml, .github/workflows/ci.yaml
See https://github.com/codecov/feedback/issues/264
This PR reverts the codecov v4 upgrade because dependabot PRs cannot upload coverage reports.
=> revert codecov action upgrade

Makefile, internal/controller/kokumetricsconfig_controller.go, internal/controller/kokumetricsconfig_controller_test.go
Updating the status during initial data gather is causing the operator to generate invalid reports.
Here is the scenario:
1. a cluster was created in the afternoon on 2-19.
2. the operator was installed on 2-20.
3. During initial data gathering, we start gathering data from 14 days ago. As we progress thru the days with no data, we set the status with the last successful query time and the message that no data was collected. Each of these status updates causes another reconciliation. 
4. While we progress thru the first reconciliation, we [do not gather the data on the 19th because it is incomplete data](https://github.com/project-koku/koku-metrics-operator/blob/main/internal/controller/kokumetricsconfig_controller.go#L829-L836).
5. We gather all of the 2-20 data and ship the payload. …
=> [COST-4624] do not show progress update during initial data gather

Makefile, internal/controller/kokumetricsconfig_controller.go, internal/controller/kokumetricsconfig_controller_test.go
Ideally, we would update [this validation](https://github.com/project-koku/koku-metrics-operator/blob/main/api/v1beta1/metricsconfig_types.go#L153) value to prevent the creation of a CR with an upload_cycle less than 60, however, already existing CRs will prevent the operator from upgrading if that value is less than 60. This PR will update the spec to set the value to 60 if it is less than 60. In a future release, we can update the validation to enforce the correct min value.
=> [COST-4528] set minimum upload_cycle to 60

Makefile, costmanagement-metrics-operator/3.2.1/manifests/costmanagement-metrics-operator.clusterserviceversion.yaml
The downstream version of the operator does not include the `v` in the ClusterServiceVersion, so this PR removes it.
=> fix the name of the csv

.github/workflows/ci-manual.yaml
Problem: 
From past few weeks, s390x action was failing
https://github.com/project-koku/koku-metrics-operator/actions/runs/8504450552
This was due to the fact that ibm cloud uses virtual interface now for network attachment
The old code uses primary network interface for attachment which is the old approach
Solution:
Made the code change to fetch virtual adapter information while creating floating ip-s
passing action:
https://github.com/ShivangGoswami/koku-metrics-operator/actions/runs/8528837180/job/23363332648
=> S390x GitHub action: change floating ip assignment from network interface to vni

.github/dependabot.yaml
* create a group for the testing frameworks -> these almost always update concurrently
* add the operator-framework to the k8s group
* create a group for prometheus
=> update dependabot groups

internal/collector/queries.go, internal/collector/test_files/test_data/persistentvolumeclaim-capacity-bytes
* `kube_persistentvolume_capacity_bytes` contains data for every PV and it's result actually matches the the value defined in the PV definition.
=> [COST-5032] switch to kube_persistentvolume_capacity_bytes

config/manifests/bases/koku-metrics-operator.clusterserviceversion.yaml, docs/csv-description.md
Add `features.operators.openshift.io` annotations for (cnf, cni, csi) to the cluster service version(csv). [Docs on defining CSVs](https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs).
=> Add  feature annotations

.pre-commit-config.yaml
Reverts project-koku/koku-metrics-operator#526
=> Revert "Update pre-commit hook golangci/golangci-lint to v1.64.8"
